/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END
#include "MainPage.h"

_Page *MainPage;
_IconView *PageIconView;

u8 *BmpBuf_Sys;
u32 sysSize;

u8 *BmpBuf_CurValue;
u32 curValueSize;

u8 *BmpBuf_BreakLog;
u32 breakLogSize;

u8 *BmpBuf_LinkList;
u32 linklistSize;

u8 *Bmp_TaskList;
u32 tasklistSize;

u8 *BmpBuf_Curve;
u32 curveSize;



#define ID_WINDOW_0 (GUI_ID_USER + 0x3E)
#define ID_ICONVIEW_0 (GUI_ID_USER + 0x3F)

static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 64, 800, 416, 0, 0x0, 0 },
  { ICONVIEW_CreateIndirect, "Iconview", ID_ICONVIEW_0, 0, 0, 800, 414, 0, 0x00A000A0, 0 },
};

static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
		//页面图标控件
		hItem = WM_GetDialogItem(pMsg->hWin,ID_ICONVIEW_0);
		ICONVIEW_SetTextColor(hItem, ICONVIEW_CI_UNSEL, GUI_BLUE);
		ICONVIEW_SetTextColor(hItem, ICONVIEW_CI_SEL, GUI_WHITE);
		//ICONVIEW_SetBkColor(hItem,ICONVIEW_CI_BK,GUI_CYAN);
		ICONVIEW_SetFrame(hItem, GUI_COORD_X, 32);//设置图标到IconView边框的间距
		ICONVIEW_SetFrame(hItem, GUI_COORD_Y, 16);
		ICONVIEW_SetSpace(hItem, GUI_COORD_X, 32);//设置图标和图标之间的间距
		ICONVIEW_SetSpace(hItem, GUI_COORD_Y, 32);
		ICONVIEW_SetFont(hItem,&GUI_FontHZ16);
		ICONVIEW_AddStreamedBitmapItem(hItem,BmpBuf_Sys,"系统信息");
		ICONVIEW_AddStreamedBitmapItem(hItem,BmpBuf_CurValue,"实时数据");
  		ICONVIEW_AddStreamedBitmapItem(hItem,BmpBuf_BreakLog,"断电日志");
		ICONVIEW_AddStreamedBitmapItem(hItem,BmpBuf_LinkList,"关联信息");
		ICONVIEW_AddStreamedBitmapItem(hItem,BmpBuf_Curve,"历史曲线");
		ICONVIEW_AddStreamedBitmapItem(hItem,Bmp_TaskList,"任务列表");
		WM_SetFocus(hItem);//页面聚焦到界面选择控件
		PageIconView->Id = hItem;
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_ICONVIEW_0: // Notifications sent by 'Iconview'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
       
        break;
      case WM_NOTIFICATION_RELEASED:
     
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        
        break;
      case WM_NOTIFICATION_SCROLL_CHANGED:
        
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
       
        break;
      }
      break;
    }
    break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

WM_HWIN CreateMainPage(void) 
{
	WM_HWIN hWin;
	
	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	MainPage->Id = hWin;
	MainPage->prePage = hWin;
	return hWin;
}
//-----------------------------------------------------------------------------------页面对按键的处理---------------------------------------------------------//
static WM_HWIN EnterPage(void)
{
	SetStatusBarTitle("矿用本安型综合分站");
	WM_ShowWindow(MainPage->Id);
	WM_SetFocus(PageIconView->Id);//页面聚焦到界面选择控件
	return 0;
}

static void ExitPage(void)
{
	WM_HideWindow(MainPage->Id);
}

//上
static void UpKeyDeal(void)
{
	GUI_SendKeyMsg(GUI_KEY_LEFT,1);
}

//下
static void DownKeyDeal(void)
{
	GUI_SendKeyMsg(GUI_KEY_RIGHT,1);
}

//MOVE
static void MoveKeyDeal(void)
{

}

static void EnterKeyLongDeal()
{

}
//确定键按下
static void EnterKeyDeal(void)
{
	switch(ICONVIEW_GetSel(PageIconView->Id))
	{
		case 0:
			SetStatusBarTitle("系统信息");
			PageJump(SysInfoPage);
			break;
		
		case 1:
			SetStatusBarTitle("实时数据");
			PageJump(CurValuePage);
			break;
		
		case 2:
			SetStatusBarTitle("断电日志");
			PageJump(PowerOffLogPage);
			break;
			
		case 3:
			SetStatusBarTitle("关联信息");
			PageJump(LinkListPage);
			break;
		
		case 4:
			SetStatusBarTitle("历史曲线");
			PageJump(HistoryCruvePage);
			break;
		
		case 5:
			SetStatusBarTitle("任务列表");
			PageJump(TaskListPage);
			break;
	}
}

//退出
static void ExitKeyDeal(void)
{

}

void MainPageInit(void)
{
	FIL *bmpfile;
	unsigned int br;
	MainPage = GuiMalloc(sizeof(_Page));
	
	MainPage->EnterPage = EnterPage;
	MainPage->ExitPage = ExitPage;
	MainPage->UpKeyDeal = UpKeyDeal;
	MainPage->DownKeyDeal = DownKeyDeal;
	MainPage->MoveKeyDeal = MoveKeyDeal;
	MainPage->EnterKeyLongDeal = EnterKeyLongDeal;
	MainPage->EnterKeyDeal = EnterKeyDeal;
	MainPage->ExitKeyDeal = ExitKeyDeal;
	PageIconView = GuiMalloc(sizeof(_IconView));

	//系统信息图标
	bmpfile = GuiMalloc(sizeof(FIL));
	f_open(bmpfile,"0:/综合分站图片/主界面/sysinfo.dta",FA_READ);
	GUI_DispStringAt("正在读取：0:/综合分站图片/主界面/sysinfo.dta",100,132);
	sysSize = bmpfile->obj.objsize;
	BmpBuf_Sys = GuiMalloc(sysSize);
	f_read(bmpfile,BmpBuf_Sys,sysSize,&br);
	f_close(bmpfile);
	
	//实时数据图标
	f_open(bmpfile,"0:/综合分站图片/主界面/curvalues.dta",FA_READ);
	GUI_DispStringAt("正在读取：0:/综合分站图片/主界面/curvalues.dta",100,164);
	curValueSize = bmpfile->obj.objsize;
	BmpBuf_CurValue = GuiMalloc(curValueSize);
	f_read(bmpfile,BmpBuf_CurValue,curValueSize,&br);
	f_close(bmpfile);
	
	//历史曲线图标
	f_open(bmpfile,"0:/综合分站图片/主界面/historycurve.dta",FA_READ);
	GUI_DispStringAt("正在读取：0:/综合分站图片/主界面/historycurve.dta",100,196);
	curveSize = bmpfile->obj.objsize;
	BmpBuf_Curve = GuiMalloc(curveSize);
	f_read(bmpfile,BmpBuf_Curve,curveSize,&br);
	f_close(bmpfile);
	
	//关联信息图标
	f_open(bmpfile,"0:/综合分站图片/主界面/linklist.dta",FA_READ);
	GUI_DispStringAt("正在读取：0:/综合分站图片/主界面/linklist.dta",100,228);
	linklistSize = bmpfile->obj.objsize;
	BmpBuf_LinkList = GuiMalloc(linklistSize);
	f_read(bmpfile,BmpBuf_LinkList,linklistSize,&br);
	f_close(bmpfile);
	
	//断电日志图标
	f_open(bmpfile,"0:/综合分站图片/主界面/breaklog.dta",FA_READ);
	GUI_DispStringAt("正在读取：0:/综合分站图片/主界面/breaklog.dta",100,260);
	breakLogSize = bmpfile->obj.objsize;
	BmpBuf_BreakLog = GuiMalloc(breakLogSize);
	f_read(bmpfile,BmpBuf_BreakLog,breakLogSize,&br);
	f_close(bmpfile);
	
	//任务列表图标
	f_open(bmpfile,"0:/综合分站图片/主界面/tasklist.dta",FA_READ);
	GUI_DispStringAt("正在读取：0:/综合分站图片/主界面/tasklist.dta",100,292);
	tasklistSize = bmpfile->obj.objsize;
	Bmp_TaskList = GuiMalloc(tasklistSize);
	f_read(bmpfile,Bmp_TaskList,tasklistSize,&br);
	f_close(bmpfile);
	GuiFree(bmpfile);
}
/*************************** End of file ****************************/

